---01
SELECT *
FROM EMP
WHERE ENAME LIKE '%S';

---02
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 30 AND JOB = 'SALESMAN'; 

---03(1)
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE (DEPTNO = 20 OR DEPTNO = 30)
AND SAL > 2000;

---03(2)

SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE (DEPTNO = 20 OR DEPTNO = 30)

INTERSECT

SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE SAL > 2000;

---04
SELECT *
FROM EMP
WHERE NOT(SAL >= 2000 AND SAL <=3000);

---05
SELECT ENAME, EMPNO, SAL, DEPTNO
FROM EMP
WHERE ENAME LIKE '%E%'
    AND DEPTNO = 30
    AND NOT(SAL >=1000 AND SAL <=2000);
    
---06
SELECT *
FROM EMP
WHERE COMM IS NULL
    AND MGR IS NOT NULL
    AND (JOB = 'MANAGER' OR JOB = 'CLERK')
    AND NOT (ENAME LIKE '_L%');
