---01
SELECT 
    DEPTNO, 
    TRUNC(AVG(SAL)) AS AVG_SAL, 
    MAX(SAL) AS MAX_SAL,
    MIN(SAL) AS MIN_SAL,
    COUNT(*) AS CNT
FROM EMP
GROUP BY DEPTNO;

---02
SELECT 
    JOB,
    COUNT(*)
FROM EMP
GROUP BY JOB
HAVING COUNT(*) >= 3;

---03
SELECT 
    TO_CHAR(HIREDATE, 'YYYY') AS HIRE_YEAR,
    DEPTNO,
    COUNT(*) AS CNT
FROM EMP
GROUP BY TO_CHAR(HIREDATE, 'YYYY'), DEPTNO
ORDER BY HIRE_YEAR, DEPTNO;

---04
SELECT
    NVL2(COMM, 'O', 'X') AS EXIST_COMM,
    COUNT(*) AS CNT
FROM EMP
GROUP BY NVL2(COMM, 'O', 'X');
