--1
SELECT E.JOB, E.EMPNO, E.ENAME, E.SAL, D.DEPTNO, D.DNAME
FROM EMP E
JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
WHERE JOB = 
(
    SELECT JOB
    FROM EMP
    WHERE ENAME = 'ALLEN'
);

--2
SELECT 
    E.EMPNO,
    E.ENAME,
    D.DNAME,
    E.HIREDATE,
    D.LOC,
    E.SAL,
    S.GRADE
FROM EMP E
JOIN DEPT D
    ON E.DEPTNO = D.DEPTNO
JOIN SALGRADE S
    ON E.SAL BETWEEN S.LOSAL AND S.HISAL
WHERE E.SAL > (
    SELECT AVG(SAL)
    FROM EMP)
ORDER BY E.SAL DESC;

--3
SELECT
    E.EMPNO,
    E.ENAME,
    E.JOB,
    D.DEPTNO,
    D.DNAME,
    D.LOC
FROM EMP E
JOIN DEPT D
    ON E.DEPTNO = D.DEPTNO
WHERE D.DEPTNO = 10
    AND E.JOB NOT IN
        (SELECT JOB
        FROM EMP
        WHERE DEPTNO = 30);
        
--4(다중행 함수(MAX) 사용)
SELECT
    E.EMPNO,
    E.ENAME,
    E.SAL ,
    S.GRADE
FROM EMP E
JOIN SALGRADE S
    ON E.SAL BETWEEN S.LOSAL AND S.HISAL
WHERE E.SAL > (SELECT MAX(SAL)
                FROM EMP
                WHERE JOB = 'SALESMAN')
ORDER BY E.EMPNO ASC;

--4(다중행 함수(MAX) 사용X)
SELECT
    E.EMPNO,
    E.ENAME,
    E.SAL ,
    S.GRADE
FROM EMP E
JOIN SALGRADE S
    ON E.SAL BETWEEN S.LOSAL AND S.HISAL
WHERE E.SAL > ALL(SELECT SAL
                    FROM EMP
                    WHERE JOB = 'SALESMAN')
ORDER BY E.EMPNO ASC;
