---01
SELECT E.DEPTNO, DNAME, EMPNO, ENAME, SAL
FROM EMP E, DEPT D
WHERE 
    E.DEPTNO = D.DEPTNO
    AND SAL > 2000;

---02
SELECT 
    E.DEPTNO,
    D.DNAME,
    TRUNC(AVG(SAL)) AS AVG_SAL,
    MAX(SAL) AS MAX_SAL,
    MIN(SAL) AS MIN_SAL,
    COUNT(*) AS CNT
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
GROUP BY E.DEPTNO, D.DNAME
ORDER BY E.DEPTNO;

---03
SELECT D.DEPTNO,DNAME, EMPNO, ENAME, JOB, SAL
FROM DEPT D
LEFT OUTER JOIN EMP E
ON E.DEPTNO = D.DEPTNO;

---04
SELECT 
    D.DEPTNO,
    D.DNAME,
    E.EMPNO,
    E.ENAME,
    E.MGR,
    E.SAL,
    E.DEPTNO AS EMP_DEPTNO,
    S.LOSAL,
    S.HISAL,
    S.GRADE,
    M.EMPNO AS MGR_EMPNO,
    M.ENAME AS MGR_ENAME
FROM DEPT D
LEFT OUTER JOIN EMP E
    ON E.DEPTNO = D.DEPTNO
LEFT OUTER JOIN SALGRADE S
    ON E.SAL BETWEEN S.LOSAL AND S.HISAL
LEFT OUTER JOIN EMP M
    ON E.MGR = M.EMPNO
ORDER BY D.DEPTNO;
